Replace usage of deprecated `distutils`
Summary:
`distutils` has been deprecated since Python 3.10, and [removed in Python 3.12](https://docs.python.org/3/whatsnew/3.12.html#distutils).

Existing usage will now raise the following error under Python 3.12+:

```
ModuleNotFoundError: No module named 'distutils'
```

This diff replaces `distutils` usage according to [PEP-632 migration advice](https://peps.python.org/pep-0632/#migration-advice).

Reviewed By: fried

Differential Revision: D73942943

fbshipit-source-id: f18fba837d9a31fda861c9c63647dcf858122adb